### ISSUE TITLE
Name similar to npx - dotnetx / dotnex

### ISSUE THREAD

**Issue by lonix1** [piraces/dotnet-tool-run#1]
This is a really nice tool. Thanks!

I like how similar it is to `npx`.

The name however is really hard to remember! :smile: It would be nice to have an alias like `dotnetx` or `dotnex`.

It could be added as an alias (not to replace `dotnet-tool-run`) so that it's backwards compatible.

**Comment by piraces** [comment]
Hi @lonix1, 

That is a great idea!! I will take a look into it and keep you updated 😄 

Thanks!!

**Comment by lonix1** [comment]
I just looked at the [nuget download stats](https://www.nuget.org/packages/dotnet-tool-run/). Not many people are using this (YET.. but that will change!), so maybe we don't have to worry about backwards compatibility.

**Comment by piraces** [comment]
Thank you very much for your suggestion @lonix1 !!

I have renamed the package to `dotnex`, because `dotnetx` already exists in nuget.org. Nevertheless, I found the name much more convenient, shorter, easier to remember and similar to npx.

About backwards compatibility, I opted to deprecate the package and redirect potential new users to the new package (which can be seen in the [old nuget page](https://www.nuget.org/packages/dotnet-tool-run/)).

I'm very happy with the name change, so thank you! 😄
